name: Update Generated File

on:
  repository_dispatch:
    types: [re_filter_lists_update]

jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout shadowrocket-config repository
      uses: actions/checkout@v3

    - name: Clone Re-filter-lists repository
      run: |
        git clone https://github.com/lrlunin/Re-filter-lists.git
        REPO_NAME=$(basename Re-filter-lists)
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        CONFIG_NAME=lunin_2.conf
        echo "CONFIG_NAME=$CONFIG_NAME" >> $GITHUB_ENV 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python generate_conf.py "$REPO_NAME" "$CONFIG_NAME"

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      id: commit_step
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git add "$CONFIG_NAME"
        git commit -m "Update generated file"
        git push https://$GH_TOKEN@github.com/lrlunin/shadowrocket-config.git
        {
          echo 'git_diff<<EOF'
          git diff HEAD^ HEAD -U0 | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)'
          echo EOF
        } >> $GITHUB_ENV

    - name: Report to the telegram group
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
          -d "chat_id=$CHAT_ID" \
          -d "text="Конфигурация для `lunin_2.conf` в Shadowrocket обновлена:\n```\n${{ steps.commit_step.outputs.git_diff }}```\n\nПожалуйста нажмите пункт Update."
